### ISSUE TITLE
Question about an error in the logs

### ISSUE THREAD

**Issue by dmapr** [Smartling/android-repository#6]
@andriipanasiuk, not so much an issue as a question: from time to time I see these error entries in the log
 

> E/SmartlingSdk( 8954): Can't create view android.support.v7.view.menu.ActionMenuItemView
E/SmartlingSdk(11130): Can't create view android.support.v7.widget.ActionBarOverlayLayout
E/SmartlingSdk(11130): Can't create view android.support.v7.widget.ContentFrameLayout
E/SmartlingSdk(11130): Can't create view android.support.v7.widget.ActionBarContainer
E/SmartlingSdk(11130): Can't create view android.support.v7.widget.Toolbar
E/SmartlingSdk(11130): Can't create view android.support.v7.widget.ActionBarContextView

Is this something to worry about?

**Comment by andriipanasiuk** [comment]
It's not an issue, it's more like confusing logs from our custom `LayoutInflater`.
After I reworked it to fix the other issue you created (https://github.com/Smartling/android-repository/issues/7) these logs disappeared and all the widgets from `appcompat-v7` library are creating appropriately.
