### ISSUE TITLE
Incorrect toolbar title color for collapsing toolbars

### ISSUE THREAD

**Issue by dmapr** [Smartling/android-repository#7]
When building with the Smartling SDK the toolbar text color is wrong for activities using collapsible toolbars. The correct color in the example below is white, but with the Smartling SDK it becomes black.

Attached is an example project (with the Samrtling SDK commented out in the app/build.gradle). On the main activity click the toolbar button to launch the collapsing toolbar one. The SDK version is 2.3.2.

![expanded-smartling](https://cloud.githubusercontent.com/assets/1417338/24559855/1adf0224-15f5-11e7-8218-2034bb6a2dec.png)
![collapsed-smartling](https://cloud.githubusercontent.com/assets/1417338/24559857/1ae02460-15f5-11e7-8721-2a0316e5cd02.png)
![expanded](https://cloud.githubusercontent.com/assets/1417338/24559854/1adc5b32-15f5-11e7-9b26-9f3748224e8b.png)
![collapsed](https://cloud.githubusercontent.com/assets/1417338/24559856/1adf65d4-15f5-11e7-9d49-1b8f33130cd2.png)

[SmartlingMDN.zip](https://github.com/Smartling/android-repository/files/886348/SmartlingMDN.zip)

**Comment by andriipanasiuk** [comment]
Hi @dmapr. 
The reason of this issue was `Toolbar` widget was incorrectly inflated, thus theme wasn't applied correctly to it.
Version *2.3.3* fixes this issue. Welcome to use it.
Please give me your feedback after you use new version.
Thanks!

**Comment by dmapr** [comment]
Hi @andriipanasiuk,

With 2.3.3 the toolbar issue is gone. If I run into anything else I'll file new issues accordingly. 

Thanks!

**Comment by andriipanasiuk** [comment]
Sure,
thank you!
